#pragma once

#include <wx/defs.h>

#ifndef NESORA_IDS_H
#define NESORA_IDS_H

enum {
    ID_Hello = wxID_HIGHEST,
    ID_EXIT,
    nsID_SPEAK_BUTTON,
    nsID_SING_BUTTON,
    nsID_VOICE_MAKE_BUTTON,
    nsID_SPEAK_PANEL,
    nsID_SING_PANEL,
    nsID_VOICE_MAKE_PANEL,
    
    nsID_VOICEMAKEPANEL_ROSENBERGWAVE_T1SLIDER,
    nsID_VOICEMAKEPANEL_ROSENBERGWAVE_T2SLIDER,
    nsID_VOICEMAKEPANEL_ROSENBERGWAVE_PLAY_BUTTON,
    nsID_VOICEMAKEPANEL_ROSENBERGWAVE_STOP_BUTTON,

    nsID_TOOLBAR_SPEAK_BUTTON,
    nsID_TOOLBAR_SING_BUTTON,
    nsID_TOOLBAR_VOICE_MAKE_BUTTON,
};

#endif // NESORA_IDS_H